### 8.1 (유학생) 서류 조회하기
// @no-log
GET {{host_url}}/v1/users/user-owner-job-postings/{{document.API_8_1.id}}/documents/summaries
Authorization: Bearer {{access_token}}

### 8.2 (고용주) 서류 조회하기
// @no-log
GET {{host_url}}/v1/owners/user-owner-job-postings/{{document.API_8_2.id}}/documents/summaries
Authorization: Bearer {{access_token}}

### 8.3 (유학생/고용주) 시간제 취업 허가서 조회하기
// @no-log
GET {{host_url}}/v1/documents/{{document.API_8_3.id}}/part-time-employment-permit/details
Authorization: Bearer {{access_token}}

### 8.4 (유학생/고용주) 근로 계약서 조회하기
// @no-log
GET {{host_url}}/v1/documents/{{document.API_8_4.id}}/standard-labor-contract/details
Authorization: Bearer {{access_token}}

### 8.5 (유학생/고용주) 통합 신청서 조회하기
// @no-log
GET {{host_url}}/v1/documents/{{document.API_8_5.id}}/integrated-application/details
Authorization: Bearer {{access_token}}

### 8.6 (유학생) 시간제 취업허가서 생성하기
// @no-log
POST {{host_url}}/v1/users/user-owner-job-postings/{{document.API_8_6.id}}/documents/part-time-employment-permits
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "first_name": "{{document.API_8_6.first_name}}",
  "last_name": "{{document.API_8_6.last_name}}",
  "major": "{{document.API_8_6.major}}",
  "term_of_completion": {{document.API_8_6.term_of_completion}},
  "phone_number": "{{document.API_8_6.phone_number}}",
  "email": "{{document.API_8_6.email}}"
}

### 8.17 (유학생) 서류 컨펌하기
// @no-log
PATCH {{host_url}}/v1/users/documents/{{document.API_8_17.id}}/status/confirmation
Authorization: Bearer {{access_token}}

