### 8.1 (유학생) 서류 조회하기
// @no-log
GET {{host_url}}/v1/users/user-owner-job-postings/{{document.API_8_1.id}}/documents/summaries
Authorization: Bearer {{access_token}}

### 8.2 (고용주) 서류 조회하기
// @no-log
GET {{host_url}}/v1/owners/user-owner-job-postings/{{document.API_8_2.id}}/documents/summaries
Authorization: Bearer {{access_token}}

### 8.3 (유학생/고용주) 시간제 취업 허가서 조회하기
// @no-log
GET {{host_url}}/v1/documents/{{document.API_8_3.id}}/part-time-employment-permit/details
Authorization: Bearer {{access_token}}

### 8.4 (유학생/고용주) 근로 계약서 조회하기
// @no-log
GET {{host_url}}/v1/documents/{{document.API_8_4.id}}/standard-labor-contract/details
Authorization: Bearer {{access_token}}

### 8.5 (유학생/고용주) 통합 신청서 조회하기
// @no-log
GET {{host_url}}/v1/documents/{{document.API_8_5.id}}/integrated-application/details
Authorization: Bearer {{access_token}}

### 8.6 (유학생) 시간제 취업허가서 생성하기
// @no-log
POST {{host_url}}/v1/users/user-owner-job-postings/{{document.API_8_6.id}}/documents/part-time-employment-permits
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "first_name": "{{document.API_8_6.first_name}}",
  "last_name": "{{document.API_8_6.last_name}}",
  "major": "{{document.API_8_6.major}}",
  "term_of_completion": {{document.API_8_6.term_of_completion}},
  "phone_number": "{{document.API_8_6.phone_number}}",
  "email": "{{document.API_8_6.email}}"
}

### 8.7 (유학생) 근로 계약서 생성하기
// @no-log
POST {{host_url}}/v1/users/user-owner-job-postings/{{document.API_8_7.id}}/documents/standard-labor-contracts
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "first_name" : "{{document.API_8_7.first_name}}",
  "last_name" : "{{document.API_8_7.last_name}}",
  "address" :
  {
    "address_name" : "{{document.API_8_7.address.address_name}}",
    "region_1depth_name" : "{{document.API_8_7.address.region_1depth_name}}",
    "region_2depth_name" : "{{document.API_8_7.address.region_2depth_name}}",
    "region_3depth_name" : "{{document.API_8_7.address.region_3depth_name}}",
    "region_4depth_name" : "{{document.API_8_7.address.region_4depth_name}}",
    "address_detail" : "{{document.API_8_7.address.address_detail}}",
    "longitude" : {{document.API_8_7.address.longitude}},
    "latitude" : {{document.API_8_7.address.latitude}}
  },
  "phone_number" : "{{document.API_8_7.phone_number}}",
  "signature_base64" : "{{document.API_8_7.signature_base64}}"
}

### 8.8 (유학생) 통합 신청서 생성하기
// @no-log
POST {{host_url}}/v1/users/user-owner-job-postings/{{document.API_8_8.id}}/documents/integrated-applications
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "first_name" : "{{document.API_8_8.first_name}}",
  "last_name" : "{{document.API_8_8.last_name}}",
  "birth" : "{{document.API_8_8.birth}}",
  "gender" : "{{document.API_8_8.gender}}",
  "nationality" : "{{document.API_8_8.nationality}}",
  "tele_phone_number" : "{{document.API_8_8.tele_phone_number}}",
  "cell_phone_number" : "{{document.API_8_8.cell_phone_number}}",
  "is_accredited" : {{document.API_8_8.is_accredited}},
  "school_name" : "{{document.API_8_8.school_name}}",
  "school_phone_number" : "{{document.API_8_8.school_phone_number}}",
  "new_work_place_name" : "{{document.API_8_8.new_work_place_name}}",
  "new_work_place_registration_number" : "{{document.API_8_8.new_work_place_registration_number}}",
  "new_work_place_phone_number" : "{{document.API_8_8.new_work_place_phone_number}}",
  "annual_income_amount" : {{document.API_8_8.annual_income_amount}},
  "occupation" : "{{document.API_8_8.occupation}}",
  "email" : "{{document.API_8_8.email}}",
  "signature_base64" : "{{document.API_8_8.signature_base64}}",
  "address" : {
    "address_name" : "{{document.API_8_8.address.address_name}}",
    "region_1depth_name" : "{{document.API_8_8.address.region_1depth_name}}",
    "region_2depth_name" : "{{document.API_8_8.address.region_2depth_name}}",
    "region_3depth_name" : "{{document.API_8_8.address.region_3depth_name}}",
    "region_4depth_name" : "{{document.API_8_8.address.region_4depth_name}}",
    "address_detail" : "{{document.API_8_8.address.address_detail}}",
    "longitude" : {{document.API_8_8.address.longitude}},
    "latitude" : {{document.API_8_8.address.latitude}}
  }
}

### 8.9 (유학생) 서류 재검토 요청하기
// @no-log
POST {{host_url}}/v1/users/documents/{{document.API_8_9.id}}/status/requestion
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "reason" : "{{document.API_8_9.reason}}"
}

### 8.10 (유학생) 시간제 취업허가서 수정하기
// @no-log
PUT {{host_url}}/v1/users/documents/{{document.API_8_10.id}}/part-time-employment-permits
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "first_name": "{{document.API_8_10.first_name}}",
  "last_name": "{{document.API_8_10.last_name}}",
  "major": "{{document.API_8_10.major}}",
  "term_of_completion": {{document.API_8_10.term_of_completion}},
  "phone_number": "{{document.API_8_10.phone_number}}",
  "email": "{{document.API_8_10.email}}"
}

### 8.11 (고용주) 시간제 취업허가서 수정하기
// @no-log
PUT {{host_url}}/v1/owners/documents/{{document.API_8_10.id}}/part-time-employment-permits
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "company_name" : "{{document.API_8_11.company_name}}",
  "company_registration_number" : "{{document.API_8_11.company_registration_number}}",
  "job_type" : "{{document.API_8_11.job_type}}",
  "name" : "{{document.API_8_11.name}}",
  "phone_number" : "{{document.API_8_11.phone_number}}",
  "signature_base64" : "{{document.API_8_11.signature_base64}}",
  "work_period" : "{{document.API_8_11.work_period}}",
  "hourly_rate" : {{document.API_8_11.hourly_rate}},
  "work_days_weekdays" : "{{document.API_8_11.work_days_weekdays}}",
  "work_days_weekends" : "{{document.API_8_11.work_days_weekends}}",
  "address" :
  {
    "address_name" : "{{document.API_8_11.address.address_name}}",
    "region_1depth_name" : "{{document.API_8_11.address.region_1depth_name}}",
    "region_2depth_name" : "{{document.API_8_11.address.region_2depth_name}}",
    "region_3depth_name" : "{{document.API_8_11.address.region_3depth_name}}",
    "region_4depth_name" : "{{document.API_8_11.address.region_4depth_name}}",
    "address_detail" : "{{document.API_8_11.address.address_detail}}",
    "longitude" : {{document.API_8_11.address.longitude}},
    "latitude" : {{document.API_8_11.address.latitude}}
  }
}

### 8.12 (유학생) 근로 계약서 수정하기
// @no-log
PUT {{host_url}}/v1/users/documents/{{document.API_8_12.id}}/standard-labor-contracts
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "first_name" : "{{document.API_8_12.first_name}}",
  "last_name" : "{{document.API_8_12.last_name}}",
  "address" :
  {
    "address_name" : "{{document.API_8_12.address.address_name}}",
    "region_1depth_name" : "{{document.API_8_12.address.region_1depth_name}}",
    "region_2depth_name" : "{{document.API_8_12.address.region_2depth_name}}",
    "region_3depth_name" : "{{document.API_8_12.address.region_3depth_name}}",
    "region_4depth_name" : "{{document.API_8_12.address.region_4depth_name}}",
    "address_detail" : "{{document.API_8_12.address.address_detail}}",
    "longitude" : {{document.API_8_12.address.longitude}},
    "latitude" : {{document.API_8_12.address.latitude}}
  },
  "phone_number" : "{{document.API_8_12.phone_number}}",
  "signature_base64" : "{{document.API_8_12.signature_base64}}"
}


### 8.17 (유학생) 서류 컨펌하기
// @no-log
PATCH {{host_url}}/v1/users/documents/{{document.API_8_17.id}}/status/confirmation
Authorization: Bearer {{access_token}}

