### 7.1 (유학생) 이력서 조회하기
// @no-log
GET {{host_url}}/v1/users/resumes/details
Authorization: Bearer {{access_token}}

### 7.2 (유학생) 경력 상세 조회하기
// @no-log
GET {{host_url}}/v1/users/resumes/work-experiences/{{resume.API_7_2.id}}/details
Authorization: Bearer {{access_token}}

### 7.19 (고용주) 이력서 조회하기
// @no-log
GET {{host_url}}/v1/owners/user-owner-job-postings/{{resume.API_7_19.id}}/users/resumes/details
Authorization: Bearer {{access_token}}