
### 8.11 (고용주) 시간제 취업허가서 수정하기
// @no-log
PUT {{host_url}}/v1/owners/documents/{{part_time_employment_permits_id}}/part-time-employment-permits
Authorization: Bearer {{owner_access_token}}
Content-Type: application/json

{
  "company_name" : "{{documentEntity.API_8_11.company_name}}",
  "company_registration_number" : "{{documentEntity.API_8_11.company_registration_number}}",
  "job_type" : "{{documentEntity.API_8_11.job_type}}",
  "name" : "{{documentEntity.API_8_11.name}}",
  "phone_number" : "{{documentEntity.API_8_11.phone_number}}",
  "signature_base64" : "{{documentEntity.API_8_11.signature_base64}}",
  "work_period" : "{{documentEntity.API_8_11.work_period}}",
  "hourly_rate" : {{documentEntity.API_8_11.hourly_rate}},
  "work_days_weekdays" : "{{documentEntity.API_8_11.work_days_weekdays}}",
  "work_days_weekends" : "{{documentEntity.API_8_11.work_days_weekends}}",
  "addressEntity" :
  {
    "address_name" : "{{documentEntity.API_8_11.addressEntity.address_name}}",
    "region_1depth_name" : "{{documentEntity.API_8_11.addressEntity.region_1depth_name}}",
    "region_2depth_name" : "{{documentEntity.API_8_11.addressEntity.region_2depth_name}}",
    "region_3depth_name" : "{{documentEntity.API_8_11.addressEntity.region_3depth_name}}",
    "region_4depth_name" : "{{documentEntity.API_8_11.addressEntity.region_4depth_name}}",
    "address_detail" : "{{documentEntity.API_8_11.addressEntity.address_detail}}",
    "longitude" : {{documentEntity.API_8_11.addressEntity.longitude}},
    "latitude" : {{documentEntity.API_8_11.addressEntity.latitude}}
  }
}

### 8.16 (고용주) 서류 제출하기
// @no-log
PATCH {{host_url}}/v1/owners/documents/{{part_time_employment_permits_id}}/status/submission
Authorization: Bearer {{owner_access_token}}


### ~ 시간제 취업허가서 파일 생성까지.
// @no-log
POST {{host_url}}/v1/auth/login
Content-Type: application/x-www-form-urlencoded

serial_id={{auth.API_1_1_USER.serial_id}}&
password={{auth.API_1_1_USER.password}}

> {%
    client.global.set("user_access_token", response.body.data.access_token);
%}

### 8.17 (유학생) 서류 컨펌하기
// @no-log
PATCH {{host_url}}/v1/users/documents/{{part_time_employment_permits_id}}/status/confirmation
Authorization: Bearer {{user_access_token}}