### 1.1 사용자 로그인 - 유학생
// @no-log
POST {{host_url}}/v1/auth/login
Content-Type: application/x-www-form-urlencoded

serial_id={{auth.API_1_1_USER.serial_id}}&
password={{auth.API_1_1_USER.password}}

> {%
    client.global.set("user_access_token", response.body.data.access_token);
%}

### 8.7 (유학생) 근로 계약서 생성하기
// @no-log
POST {{host_url}}/v1/users/userEntity-ownerEntity-job-postings/{{user_owner_job_posting_id}}/documents/standard-labor-contracts
Authorization: Bearer {{user_access_token}}
Content-Type: application/json

{
  "first_name" : "{{documentEntity.API_8_7.first_name}}",
  "last_name" : "{{documentEntity.API_8_7.last_name}}",
  "addressEntity" :
  {
    "address_name" : "{{documentEntity.API_8_7.addressEntity.address_name}}",
    "region_1depth_name" : "{{documentEntity.API_8_7.addressEntity.region_1depth_name}}",
    "region_2depth_name" : "{{documentEntity.API_8_7.addressEntity.region_2depth_name}}",
    "region_3depth_name" : "{{documentEntity.API_8_7.addressEntity.region_3depth_name}}",
    "region_4depth_name" : "{{documentEntity.API_8_7.addressEntity.region_4depth_name}}",
    "address_detail" : "{{documentEntity.API_8_7.addressEntity.address_detail}}",
    "longitude" : {{documentEntity.API_8_7.addressEntity.longitude}},
    "latitude" : {{documentEntity.API_8_7.addressEntity.latitude}}
  },
  "phone_number" : "{{documentEntity.API_8_7.phone_number}}",
  "signature_base64" : "{{documentEntity.API_8_7.signature_base64}}"
}

### 8.1 (유학생) 서류 조회하기
// @no-log
GET {{host_url}}/v1/users/userEntity-ownerEntity-job-postings/{{user_owner_job_posting_id}}/documents/summaries
Authorization: Bearer {{user_access_token}}

> {%
    client.global.set("standard_labor_contract_id", response.body.data.standard_labor_contract.id);
%}

### 8.15 (유학생) 서류 제출하기
// @no-log
PATCH {{host_url}}/v1/users/documents/{{standard_labor_contract_id}}/status/submission
Authorization: Bearer {{user_access_token}}

### 유학생이 근로계약서 작성 및 제출 한 이후부터의 시나리오. 유학생 "근로계약서" 서명 확인용
// @no-log
POST {{host_url}}/v1/auth/login
Content-Type: application/x-www-form-urlencoded

serial_id={{auth.API_1_1_OWNER.serial_id}}&
password={{auth.API_1_1_OWNER.password}}

> {%
    client.global.set("owner_access_token", response.body.data.access_token);
%}

### 1.1 사용자 로그인 - 유학생
// @no-log
POST {{host_url}}/v1/auth/login
Content-Type: application/x-www-form-urlencoded

serial_id={{auth.API_1_1_USER.serial_id}}&
password={{auth.API_1_1_USER.password}}

> {%
    client.global.set("user_access_token", response.body.data.access_token);
%}

### 8.2 (고용주) 서류 조회하기
// @no-log
GET {{host_url}}/v1/owners/userEntity-ownerEntity-job-postings/{{user_owner_job_posting_id}}/documents/summaries
Authorization: Bearer {{owner_access_token}}

> {%
    client.global.set("standard_labor_contract_id", response.body.data.standard_labor_contract.id);
%}

### 8.13 (고용주) 근로 계약서 수정하기
// @no-log
PUT {{host_url}}/v1/owners/documents/{{standard_labor_contract_id}}/standard-labor-contracts
Authorization: Bearer {{owner_access_token}}
Content-Type: application/json

{
  "company_name" : "{{documentEntity.API_8_13.company_name}}",
  "company_registration_number" : "{{documentEntity.API_8_13.company_registration_number}}",
  "phone_number" : "{{documentEntity.API_8_13.phone_number}}",
  "name" : "{{documentEntity.API_8_13.name}}",
  "start_date" : "{{documentEntity.API_8_13.start_date}}",
  "end_date" : "{{documentEntity.API_8_13.end_date}}",
  "addressEntity" :
  {
    "address_name" : "{{documentEntity.API_8_13.addressEntity.address_name}}",
    "region_1depth_name" : "{{documentEntity.API_8_13.addressEntity.region_1depth_name}}",
    "region_2depth_name" : "{{documentEntity.API_8_13.addressEntity.region_2depth_name}}",
    "region_3depth_name" : "{{documentEntity.API_8_13.addressEntity.region_3depth_name}}",
    "region_4depth_name" : "{{documentEntity.API_8_13.addressEntity.region_4depth_name}}",
    "detail_address" : "{{documentEntity.API_8_13.addressEntity.detail_address}}",
    "longitude" : {{documentEntity.API_8_13.addressEntity.longitude}},
    "latitude" : {{documentEntity.API_8_13.addressEntity.latitude}}
  },
  "description" : "{{documentEntity.API_8_13.description}}",
  "work_day_time_list" : [
    {
      "day_of_week" : "{{documentEntity.API_8_13.work_day_time_list[0].day_of_week}}",
      "work_start_time" : "{{documentEntity.API_8_13.work_day_time_list[0].work_start_time}}",
      "work_end_time" : "{{documentEntity.API_8_13.work_day_time_list[0].work_end_time}}",
      "break_start_time" : "{{documentEntity.API_8_13.work_day_time_list[0].break_start_time}}",
      "break_end_time" : "{{documentEntity.API_8_13.work_day_time_list[0].break_end_time}}"
    },
    {
      "day_of_week" : "{{documentEntity.API_8_13.work_day_time_list[1].day_of_week}}",
      "work_start_time" : "{{documentEntity.API_8_13.work_day_time_list[1].work_start_time}}",
      "work_end_time" : "{{documentEntity.API_8_13.work_day_time_list[1].work_end_time}}",
      "break_start_time" : "{{documentEntity.API_8_13.work_day_time_list[1].break_start_time}}",
      "break_end_time" : "{{documentEntity.API_8_13.work_day_time_list[1].break_end_time}}"
    },
    {
      "day_of_week" : "{{documentEntity.API_8_13.work_day_time_list[2].day_of_week}}",
      "work_start_time" : "{{documentEntity.API_8_13.work_day_time_list[2].work_start_time}}",
      "work_end_time" : "{{documentEntity.API_8_13.work_day_time_list[2].work_end_time}}",
      "break_start_time" : "{{documentEntity.API_8_13.work_day_time_list[2].break_start_time}}",
      "break_end_time" : "{{documentEntity.API_8_13.work_day_time_list[2].break_end_time}}"
    }
  ],
  "weekly_last_days" : ["{{documentEntity.API_8_13.weekly_last_days1}}", "{{documentEntity.API_8_13.weekly_last_days2}}"],
  "hourly_rate" : {{documentEntity.API_8_13.hourly_rate}},
  "bonus" : {{documentEntity.API_8_13.bonus}},
  "additional_salary" : {{documentEntity.API_8_13.additional_salary}},
  "wage_rate" : {{documentEntity.API_8_13.wage_rate}},
  "payment_day" : {{documentEntity.API_8_13.payment_day}},
  "payment_method" : "{{documentEntity.API_8_13.payment_method}}",
  "insurance" : ["{{documentEntity.API_8_13.insurance1}}", "{{documentEntity.API_8_13.insurance2}}"],
  "signature_base64" : "{{documentEntity.API_8_13.signature_base64}}"
}

### 8.16 (고용주) 서류 제출하기
// @no-log
PATCH {{host_url}}/v1/owners/documents/{{standard_labor_contract_id}}/status/submission
Authorization: Bearer {{owner_access_token}}

### 8.17 (유학생) 서류 컨펌하기
// @no-log
PATCH {{host_url}}/v1/users/documents/{{standard_labor_contract_id}}/status/confirmation
Authorization: Bearer {{user_access_token}}