apiVersion: v1
kind: PersistentVolume
metadata:
  name: osrm-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/osrm
