apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  username: ${{ username }}
  password: ${{ password }}
  database: ${{ database }}

---

apiVersion: v1
kind: Secret
metadata:
  name: application-yml-secret
data:
  mysql-host: ${{ mysqlhost }}
  mysql-port: ${{ mysqlport }}
  mysql-username: ${{ mysqlusername }}
  mysql-password: ${{ mysqlpassword }}
  mysql-database-name: ${{ mysqldatabase }}
  redis-host: ${{ redishost }}
  redis-port: ${{ redisport }}
  mail-port: ${{ mailport }}
  mail-username: ${{ mailusername }}
  mail-password: ${{ mailpassword }}
  max-file-size: ${{ maxfilesize }}
  max-request-size: ${{ maxrequestsize }}
  server-url: ${{ serverurl }}
  client-url: ${{ clienturl }}
  cookie-domain: ${{ cookiedomain }}
  jwt-secret-key: ${{ jwtsecretkey }}
  temporary-token-expire-period: ${{ temporarytokenexpireperiod }}
  access-token-expire-period: ${{ accesstokenexpireperiod }}
  refresh-token-expire-period: ${{ refreshtokenexpireperiod }}
  aws-access-key: ${{ awsaccesskey }}
  aws-secret-key: ${{ awssecretkey }}
  aws-region: ${{ awsregion }}
  aws-s3-bucket: ${{ awss3bucket }}
  aws-s3-url: ${{ awss3url }}
  aws-s3-user-default-img-url: ${{ awss3userdefaultimgurl }}
  aws-s3-owner-default-img-url: ${{ awss3ownerdefaultimgurl }}
  part-time-employment-permit-template-path: ${{ parttimeemploymentpermittemplatepath }}
  standard-labor-contract-template-path: ${{ standardlaborcontracttemplatepath }}
  integrated-application-template-path: ${{ integratedapplicationtemplatepath }}
  osrm-url: ${{ osrmurl }}
  osrm-path: ${{ osrmpath }}
  kakao-secret-key: ${{ kakaosecretkey }}
  push-token-register-url: ${{ pushtokenregisterurl }}
  push-token-send-url: ${{ pushtokensendurl }}
  push-token-get-url: ${{ pushtokengeturl }}
  push-token-delete-url: ${{ pushtokendeleteurl }}
