### 6.1 (유학생) 지원한 공고 리스트 조회하기
GET {{host_url}}/v1/users/user-owner-job-postings/overviews?
    page=1&
    size=100&
    sorting={{posting.API_6_1.sorting}}&
    status={{posting.API_6_1.status}}
Authorization: Bearer {{access_token}}

### 6.2 (유학생) 지원한 공고 상세 조회하기
GET {{host_url}}/v1/users/user-owner-job-postings/{{posting.API_6_2.user_owner_job_posting_id}}/details
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.3 (유학생) 현재 진행중인 인터뷰 리스트 조회하기
GET http://localhost:8080/v1/users/user-owner-job-postings/briefs?
    page={{posting.API_6_3.page}}&
    size={{posting.API_6_3.size}}
Content-Type: application/json
Authorization: Bearer {{access_token}}