### 4.1 (게스트) 공고 리스트 조회하기
// @no-log
GET {{host_url}}/v1/guests/job-postings/overviews?
    page={{posting.API_4_1.page}}&
    sorting={{posting.API_4_1.sorting}}&
    size={{posting.API_4_1.size}}
Content-Type: application/json
#    type = {{posting.API_4_1.type}}

#    region_1depth={{posting.API_4_1.region_1depth_name}}&
#    region_2depth={{posting.API_4_1.region_2depth_name}}&
#    region_3depth={{posting.API_4_1.region_3depth_name}}
#    industry={{posting.API_4_1.industry}}&
#    work_period={{posting.API_4_1.work_period}}&
#    work_days_per_week={{posting.API_4_1.work_days_per_week}}&
#    working_day= {{posting.API_4_1.working_day}}&
#    working_hours= {{posting.API_4_1.working_hours}}&
#    recruitment_period= {{posting.API_4_1.recruitment_period}}&
#    employment_type = {{posting.API_4_1.employment_type}}&
#    visa = {{posting.API_4_1.visa}}



### 4.2 (게스트) 공고 상세 조회하기
// @no-log
GET {{host_url}}/v1/guests/job-postings/2/details
Content-Type: application/json


### 4.3 (유학생/고용주) 공고 리스트 조회하기
// @no-log
GET {{host_url}}/v1/job-postings/overviews?
    page={{posting.API_4_3.page}}&
    size={{posting.API_4_3.size}}&
    sorting= {{posting.API_4_3.sorting}}&
    type={{posting.API_4_3.type}}
#    region_1depth={{posting.API_4_3.region_1depth_name}}&
#    region_2depth={{posting.API_4_3.region_2depth_name}}&
#    region_3depth={{posting.API_4_3.region_3depth_name}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

#    industry={{posting.API_4_3.industry}}&
#    work_period={{posting.API_4_3.work_period}}&
#    work_days_per_week={{posting.API_4_3.work_days_per_week}}&
#    working_day= {{posting.API_4_3.working_day}}&
#    working_hours= {{posting.API_4_3.working_hours}}&
#    recruitment_period= {{posting.API_4_3.recruitment_period}}&
#    employment_type = {{posting.API_4_3.employment_type}}&
#    visa = {{posting.API_4_3.visa}}



### 4.4 (유학생/고용주) 공고 상세 조회하기
// @no-log
GET {{host_url}}/v1/job-postings/2/details
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 4.5 (유학생) 추천 공고 리스트 조회하기
// @no-log
GET {{host_url}}/v1/users/job-postings/briefs
Content-Type: application/json
Authorization: Bearer {{access_token}}



### 4.6 (고용주) 공고에 대한 지원자 리스트 조회
// @no-log
GET {{host_url}}/v1/owners/job-postings/{{posting.API_4_6.job_posting_id}}/user-owner-job-postings/users/overviews?
    page={{posting.API_4_6.page}}&
    size={{posting.API_4_6.size}}&
    sorting={{posting.API_4_6.sorting}}&
    status={{posting.API_4_6.status}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 4.7 (유학생/고용주) 공고 요약 정보 조회하기
// @no-log
GET {{host_url}}/v1/job-postings/2/summaries
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 4.8 (유학생) 공고 지원 자격 확인하기
// @no-log
GET {{host_url}}/v1/users/job-postings/{{posting.API_4_8.job_posting_id}}/validation
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 4.9 (유학생) 공고 지원하기
// @no-log
POST {{host_url}}/v1/users/job-postings/{{posting.API_4_9.job_posting_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 4.10 (고용주) 공고 등록하기
// @no-log
POST {{host_url}}/v1/owners/job-postings
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{access_token}}

--boundary
Content-Disposition: form-data; name="body"
Content-Type: application/json

{
  "title": "{{posting.API_4_10.title}}",
  "job_category": "{{posting.API_4_10.job_category}}",
  "work_day_times": [
    {
      "day_of_week": "{{posting.API_4_10.work_day_times[0].day_of_week}}",
      "work_start_time": "{{posting.API_4_10.work_day_times[0].work_start_time}}",
      "work_end_time": "{{posting.API_4_10.work_day_times[0].work_end_time}}"
    },
    {
      "day_of_week": "{{posting.API_4_10.work_day_times[1].day_of_week}}",
      "work_start_time": "{{posting.API_4_10.work_day_times[1].work_start_time}}",
      "work_end_time": "{{posting.API_4_10.work_day_times[1].work_end_time}}"
    }
  ],
  "work_period": "{{posting.API_4_10.work_period}}",
  "hourly_rate": {{posting.API_4_10.hourly_rate}},
  "employment_type": "{{posting.API_4_10.employment_type}}",
  "address": {
    "address_name": "{{posting.API_4_10.address.address_name}}",
    "region_1depth_name": "{{posting.API_4_10.address.region_1depth_name}}",
    "region_2depth_name": "{{posting.API_4_10.address.region_2depth_name}}",
    "region_3depth_name": "{{posting.API_4_10.address.region_3depth_name}}",
    "region_4depth_name": "{{posting.API_4_10.address.region_4depth_name}}",
    "address_detail": "{{posting.API_4_10.address.address_detail}}",
    "latitude": {{posting.API_4_10.address.latitude}},
    "longitude": {{posting.API_4_10.address.longitude}}
  },
  "recruitment_dead_line": "{{posting.API_4_10.recruitment_dead_line}}",
  "recruitment_number": {{posting.API_4_10.recruitment_number}},
  "gender": "{{posting.API_4_10.gender}}",
  "age_restriction": {{posting.API_4_10.age_restriction}},
  "education_level": "{{posting.API_4_10.education_level}}",
  "visa": ["D_2","D_4"],
  "recruiter_name": "{{posting.API_4_10.recruiter_name}}",
  "recruiter_email": "{{posting.API_4_10.recruiter_email}}",
  "recruiter_phone_number": "{{posting.API_4_10.recruiter_phone_number}}",
  "description": "{{posting.API_4_10.description}}",
  "preferred_conditions": "{{posting.API_4_10.preferred_conditions}}"
}

--boundary
Content-Disposition: form-data; name="image"; filename="image1.png"
Content-Type: image/png

< /Users/jjuuuunnii/Desktop/image.png

--boundary
Content-Disposition: form-data; name="image"; filename="image2.png"
Content-Type: image/png

< /Users/jjuuuunnii/Desktop/image.png

--boundary
Content-Disposition: form-data; name="image"; filename="image3.png"
Content-Type: image/png

< /Users/jjuuuunnii/Desktop/image.png

--boundary






### 4.11 (고용주) 공고 수정하기
// @no-log
PUT {{host_url}}/v1/owners/job-postings/1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{access_token}}

--boundary
Content-Disposition: form-data; name="body"
Content-Type: application/json

{
  "title": "{{posting.API_4_11.title}}",
  "job_category": "{{posting.API_4_11.job_category}}",
  "work_day_times": [
    {
      "day_of_week": "{{posting.API_4_11.work_day_times[0].day_of_week}}",
      "work_start_time": "{{posting.API_4_11.work_day_times[0].work_start_time}}",
      "work_end_time": "{{posting.API_4_11.work_day_times[0].work_end_time}}"
    },
    {
      "day_of_week": "{{posting.API_4_11.work_day_times[1].day_of_week}}",
      "work_start_time": "{{posting.API_4_11.work_day_times[1].work_start_time}}",
      "work_end_time": "{{posting.API_4_11.work_day_times[1].work_end_time}}"
    }
  ],
  "work_period": "{{posting.API_4_11.work_period}}",
  "hourly_rate": {{posting.API_4_11.hourly_rate}},
  "employment_type": "{{posting.API_4_11.employment_type}}",
  "address": {
    "address_name": "{{posting.API_4_11.address.address_name}}",
    "region_1depth_name": "{{posting.API_4_11.address.region_1depth_name}}",
    "region_2depth_name": "{{posting.API_4_11.address.region_2depth_name}}",
    "region_3depth_name": "{{posting.API_4_11.address.region_3depth_name}}",
    "region_4depth_name": "{{posting.API_4_11.address.region_4depth_name}}",
    "address_detail": "{{posting.API_4_11.address.address_detail}}",
    "latitude": {{posting.API_4_11.address.latitude}},
    "longitude": {{posting.API_4_11.address.longitude}}
  },
  "recruitment_dead_line": "{{posting.API_4_11.recruitment_dead_line}}",
  "recruitment_number": {{posting.API_4_11.recruitment_number}},
  "gender": "{{posting.API_4_11.gender}}",
  "age_restriction": {{posting.API_4_11.age_restriction}},
  "education_level": "{{posting.API_4_11.education_level}}",
  "visa": ["D_2","D_4"],
  "recruiter_name": "{{posting.API_4_11.recruiter_name}}",
  "recruiter_email": "{{posting.API_4_11.recruiter_email}}",
  "recruiter_phone_number": "{{posting.API_4_11.recruiter_phone_number}}",
  "description": "{{posting.API_4_11.description}}",
  "preferred_conditions": "{{posting.API_4_11.preferred_conditions}}",
  "deleted_img_ids": [
    {{posting.API_4_11.deleted_img_ids[0]}}, {{posting.API_4_11.deleted_img_ids[1]}}
  ]
}

--boundary
Content-Disposition: form-data; name="image"; filename="image1.png"
Content-Type: image/png

< /Users/kyeom/Desktop/team13.png

--boundary
Content-Disposition: form-data; name="image"; filename="image2.png"
Content-Type: image/png

< /Users/kyeom/Desktop/team13.png

--boundary
Content-Disposition: form-data; name="image"; filename="image3.png"
Content-Type: image/png

< /Users/kyeom/Desktop/team13.png

--boundary



### 4.12 (유학생) 북마크 추가/삭제
// @no-log
PUT {{host_url}}/v1/users/job-postings/{{posting.API_4_12.job_posting_id}}/book-marks
Content-Type: application/json
Authorization: Bearer {{access_token}}



### 4.13 (고용주) 공고 삭제하기
// @no-log
DELETE {{host_url}}/v1/owners/job-postings/{{posting.API_4_13.job_posting_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}



### 4.14 (관리자) 공고 등록 수 조회하기
// @no-log
GET {{host_url}}/v1/admins/job-postings/summaries?
    start_date = {{posting.API_4_14.start_date}}&
    end_date = {{posting.API_4_14.end_date}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 4.15 (관리자) 공고 목록 조회하기
// @no-log
GET {{host_url}}/v1/admins/job-postings/overviews?
    page={{posting.API_4_15.page}}
    &size={{posting.API_4_15.size}}
    &start_date={{posting.API_4_15.start_date}}
    &end_date={{posting.API_4_15.end_date}}
    &filter_type={{posting.API_4_15.filter_type}}
    &filter={{posting.API_4_15.filter}}
#    &sort_type={{posting.API_4_15.sort_type}}
#    &sort={{posting.API_4_15.sort}}
#    &search={{posting.API_4_15.search}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

//======================================================= API 5 =======================================================


### 5.1 (유학생) 북마크한 공고 리스트 조회하기
// @no-log
GET {{host_url}}/v1/users/book-marks/overviews?
    page={{posting.API_4_14.page}}&
    size={{posting.API_4_14.size}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 5.2 (유학생) 북마크 현황(개수) 확인하기
// @no-log
GET {{host_url}}/v1/users/book-marks/counts
Content-Type: application/json
Authorization: Bearer {{access_token}}


//======================================================= API 6 =======================================================


### 6.1 (유학생) 지원한 공고 리스트 조회하기
// @no-log
GET {{host_url}}/v1/users/user-owner-job-postings/overviews?
    page=1&
    size=100&
    sorting={{posting.API_6_1.sorting}}&
    status={{posting.API_6_1.status}}
Authorization: Bearer {{access_token}}


### 6.2 (유학생) 지원한 공고 상세 조회하기
// @no-log
GET {{host_url}}/v1/users/user-owner-job-postings/{{posting.API_6_2.user_owner_job_posting_id}}/details
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.3 (유학생) 현재 진행중인 인터뷰 리스트 조회하기
// @no-log
GET http://localhost:8080/v1/users/user-owner-job-postings/briefs?
    page={{posting.API_6_3.page}}&
    size={{posting.API_6_3.size}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.4 (유학생) 지원 현황(개수) 확인하기
// @no-log
GET {{host_url}}/v1/users/user-owner-job-postings/counts
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.5 (유학생) 공고 담당자 정보 조회하기
// @no-log
GET {{host_url}}/v1/users/user-owner-job-postings/{{posting.API_6_5.user_owner_job_posting_id}}/recruiters
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.6 (고용주) 등록한 공고 리스트 조회하기
// @no-log
GET {{host_url}}/v1/owners/job-postings/overviews?
    page={{posting.API_6_6.page}}&
    size={{posting.API_6_6.size}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.7 (고용주) 지원자 지원 상태 상세 조회
// @no-log
GET {{host_url}}/v1/owners/user-owner-job-postings/{{posting.API_6_7.user_owner_job_posting_id}}/details
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.8 (고용주) 지원자 간단 정보 조회하기
// @no-log
GET {{host_url}}/v1/owners/user-owner-job-postings/{{posting.API_6_8.user_owner_job_posting_id}}/users/briefs
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.9 (고용주) 지원 현황(개수) 확인하기
// @no-log
GET {{host_url}}/v1/owners/user-owner-job-postings/counts
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.10 (고용주) 이력서 수락/거절하기
// @no-log
PATCH {{host_url}}/v1/owners/user-owner-job-postings/{{posting.API_6_10.user_owner_job_posting_id}}/step-resume-under-review
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "is_accepted": {{posting.API_6_10.is_accepted}}
}


### 6.11 (고용주) 인터뷰 완료하기
// @no-log
PATCH {{host_url}}/v1/owners/user-owner-job-postings/{{posting.API_6_11.user_owner_job_posting_id}}/step-waiting-for-interview
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.12 (유학생) 서류 작성 완료하기
// @no-log
PATCH {{host_url}}/v1/users/user-owner-job-postings/{{posting.API_6_12.user_owner_job_posting_id}}/step-filling-out-documents
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.13 (유학생) 담당자 검토 완료
// @no-log
PATCH {{host_url}}/v1/users/user-owner-job-postings/{{posting.API_6_13.user_owner_job_posting_id}}/step-document-under-review
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.14 (유학생) 하이코리아 지원
// @no-log
PATCH {{host_url}}/v1/users/user-owner-job-postings/{{posting.API_6_14.user_owner_job_posting_id}}/step-application-in-progress
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.15 (유학생) 하이코리아 처리결과 등록하기
// @no-log
PATCH {{host_url}}/v1/users/user-owner-job-postings/{{posting.API_6_15.user_owner_job_posting_id}}/step-registering-results
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "is_approval": {{posting.API_6_15.is_approval}},
  "feedback": "{{posting.API_6_15.feedback}}"
}


### 6.16 (어드민) 공고 신청 수 조회하기
// @no-log
GET {{host_url}}/v1/admins/user-owner-job-postings/summaries?
    start_date={{posting.API_6_16.start_date}}&
    end_date={{posting.API_6_16.end_date}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.17 (어드민) 매칭 성공 수 조회하기
// @no-log
GET {{host_url}}/v1/admins/user-owner-job-postings/application-success/summaries?
    start_date={{posting.API_6_17.start_date}}&
    end_date={{posting.API_6_17.end_date}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.18 (어드민) 지원 목록 조회하기
// @no-log
GET {{host_url}}/v1/admins/user-owner-job-postings/overviews?
    page={{posting.API_6_18.page}}
    &size={{posting.API_6_18.size}}
    &start_date={{posting.API_6_18.start_date}}
    &end_date={{posting.API_6_18.end_date}}
    &sort_type={{posting.API_6_18.sort_type}}
    &sort={{posting.API_6_18.sort}}
    &filter={{posting.API_6_18.filter}}
    &filter_type={{posting.API_6_18.filter_type}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.19 (어드민) 신규 신청 조회하기
// @no-log
GET {{host_url}}/v1/admins/user-owner-job-postings/digests?
    start_date={{posting.API_6_19.start_date}}
    &end_date={{posting.API_6_19.end_date}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.20 (어드민) 누적 신청 조회하기
// @no-log
GET {{host_url}}/v1/admins/user-owner-job-postings/briefs
Content-Type: application/json
Authorization: Bearer {{access_token}}


### 6.21 (어드민) 공고 메모 수정하기
// @no-log
PATCH {{host_url}}/v1/admins/user-owner-job-postings/{{posting.API_6_21.user_owner_job_posting_id}}/memo
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "memo": "{{posting.API_6_21.memo}}"
}
