### 3.1 (유학생) 유저 프로필 조회하기
// @no-log
GET {{host_url}}/v1/users/details
Authorization: Bearer {{access_token}}

### 3.2 (고용주) 회사 정보 조회하기
// @no-log
GET {{host_url}}/v1/owners/details
Authorization: Bearer {{access_token}}

### 3.3 유저 요약 정보 조회하기
// @no-log
GET {{host_url}}/v1/users/summaries
Authorization: Bearer {{access_token}}